apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  rules:
  - host: app.192.168.64.3.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
